ALTER TABLE profiles ADD COLUMN IF NOT EXISTS email TEXT;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS profession TEXT;
ALTER TABLE reflections ADD COLUMN IF NOT EXISTS overthinking_level INTEGER DEFAULT 5;
ALTER TABLE reflections ADD COLUMN IF NOT EXISTS clarity_scores JSONB DEFAULT '{}';
